# Generated by Django 4.2.4 on 2023-08-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('descr', models.TextField(verbose_name='Tavsifi')),
                ('photo', models.ImageField(default='media/no-photo_5TKbPdH.png', upload_to='')),
            ],
            options={
                'verbose_name': 'Yangilikalar',
                'verbose_name_plural': 'Yangilikalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('descr', models.TextField(verbose_name="Ma'lumot")),
            ],
            options={
                'verbose_name': 'Tovarlar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ism')),
                ('tg_id', models.PositiveBigIntegerField(unique=True, verbose_name='Telegram id')),
                ('phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='Raqam')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Ball')),
            ],
            options={
                'verbose_name': 'Foydalanuvchilar',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Diametr')),
                ('price', models.PositiveBigIntegerField(verbose_name='Narxi')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='loyal_app.product', verbose_name='Tovar')),
            ],
            options={
                'verbose_name': 'Diametrlar',
                'verbose_name_plural': 'Diametrlar',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Bonus kod')),
                ('point', models.PositiveIntegerField(verbose_name='Bal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyal_app.user')),
            ],
            options={
                'verbose_name': 'Bonuslar',
                'verbose_name_plural': 'Bonuslar',
            },
        ),
    ]
